package com.devuloopers.knet.protocol.grpc

import com.devuloopers.knet.logger.KNetLogger
import com.google.protobuf.DescriptorProtos
import com.google.protobuf.Descriptors
import com.google.protobuf.DynamicMessage
import com.google.protobuf.util.JsonFormat
import java.util.concurrent.ConcurrentHashMap

private const val TAG = "ProtobufDynamicDecoder"

/**
 * Dynamic decoder capable of parsing arbitrary Protobuf binary payloads into
 * human-readable JSON formats using registered schema descriptors.
 *
 * This utility uses protobuf-java's [DynamicMessage] and [JsonFormat] to
 * allow on-the-fly request and response payload visualization.
 */
class ProtobufDynamicDecoder {

    /**
     * Map of fully-qualified message type names (e.g. "google.protobuf.Timestamp")
     * to their resolved descriptors.
     */
    private val descriptors = ConcurrentHashMap<String, Descriptors.Descriptor>()

    /**
     * Registers a compiled Protobuf descriptor set (.desc or .pb file generated by protoc).
     *
     * Resolves inter-file dependencies within the descriptor set iteratively.
     *
     * @param descriptorSetBytes The binary content of the compiled descriptor set file.
     */
    fun registerSchema(descriptorSetBytes: ByteArray) {
        try {
            val fileDescriptorSet = DescriptorProtos.FileDescriptorSet.parseFrom(descriptorSetBytes)
            val fileDescriptors = mutableMapOf<String, Descriptors.FileDescriptor>()

            val pendingProtos = fileDescriptorSet.fileList.toMutableList()
            var progress = true

            // Iteratively build file descriptors by resolving dependencies
            while (pendingProtos.isNotEmpty() && progress) {
                progress = false
                val iterator = pendingProtos.iterator()
                while (iterator.hasNext()) {
                    val proto = iterator.next()
                    val dependencies = proto.dependencyList.mapNotNull { fileDescriptors[it] }.toTypedArray()

                    // If all listed dependencies are already built, we can build this one
                    if (dependencies.size == proto.dependencyCount) {
                        val fileDescriptor = Descriptors.FileDescriptor.buildFrom(proto, dependencies)
                        fileDescriptors[proto.name] = fileDescriptor

                        // Index all message types within this file
                        registerMessageTypes(fileDescriptor)

                        iterator.remove()
                        progress = true
                    }
                }
            }

            if (pendingProtos.isNotEmpty()) {
                KNetLogger.warn(TAG) {
                    "Some descriptors could not be registered due to missing dependencies: " +
                        pendingProtos.joinToString { it.name }
                }
            } else {
                KNetLogger.debug(TAG) { "Successfully registered protobuf schema descriptor set." }
            }
        } catch (exception: Exception) {
            KNetLogger.error(TAG, exception) { "Failed to register protobuf schema" }
        }
    }

    /**
     * Recursively registers message descriptors defined inside a [Descriptors.FileDescriptor].
     */
    private fun registerMessageTypes(fileDescriptor: Descriptors.FileDescriptor) {
        for (descriptor in fileDescriptor.messageTypes) {
            registerDescriptor(descriptor)
        }
    }

    /**
     * Helper method to recursively register nested types.
     */
    private fun registerDescriptor(descriptor: Descriptors.Descriptor) {
        descriptors[descriptor.fullName] = descriptor
        for (nestedType in descriptor.nestedTypes) {
            registerDescriptor(nestedType)
        }
    }

    /**
     * Decodes a raw protobuf binary payload into a JSON formatted string.
     *
     * @param messageTypeName The fully-qualified name of the message type (e.g. "com.example.User").
     * @param payload The raw serialized protobuf byte array.
     * @return The JSON string representation of the message, or null if decoding fails or the schema is missing.
     */
    fun decodeToJson(messageTypeName: String, payload: ByteArray): String? {
        val descriptor = descriptors[messageTypeName] ?: run {
            KNetLogger.warn(TAG) { "No registered descriptor found for type: $messageTypeName" }
            return null
        }

        return try {
            val dynamicMessage = DynamicMessage.parseFrom(descriptor, payload)
            JsonFormat.printer().print(dynamicMessage)
        } catch (exception: Exception) {
            KNetLogger.error(TAG, exception) { "Failed to dynamically decode message of type $messageTypeName" }
            null
        }
    }

    /**
     * Clears all registered descriptors from the decoder registry.
     */
    fun clearRegistry() {
        descriptors.clear()
        KNetLogger.debug(TAG) { "Protobuf registry cleared." }
    }
}
