package com.devuloopers.knet.testingserver.http

import kotlinx.coroutines.delay
import org.springframework.http.HttpHeaders
import org.springframework.http.HttpStatus
import org.springframework.http.HttpStatusCode
import org.springframework.http.ResponseCookie
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestHeader
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import org.springframework.web.server.ServerWebExchange
import java.net.URI
import kotlin.time.Clock
import kotlin.time.Duration.Companion.milliseconds

/**
 * Canonical echo response preserving repeated request metadata for Traffic inspection.
 *
 * @property method Observed HTTP method token.
 * @property path Observed request path.
 * @property headers Ordered values grouped by case-preserved header name.
 * @property query Ordered query values grouped by parameter name.
 * @property cookies Ordered cookie values grouped by cookie name.
 * @property bodyText Unmodified textual request entity, when present.
 * @property receivedAt ISO-8601 timestamp generated by Kotlin time.
 */
data class HttpEchoResponse(
    val method: String,
    val path: String,
    val headers: Map<String, List<String>>,
    val query: Map<String, List<String>>,
    val cookies: Map<String, List<String>>,
    val bodyText: String?,
    val receivedAt: String,
)

/**
 * Result returned by authentication scenarios.
 *
 * @property authenticated Whether the expected credential form was present.
 * @property scheme Credential scheme exercised by the endpoint.
 */
data class AuthenticationResult(
    val authenticated: Boolean,
    val scheme: String,
)

/**
 * Cohesive HTTP behavior fixtures for methods, metadata, latency, redirects, cookies, and authentication.
 *
 * These endpoints deliberately describe the wire behavior being tested and contain no KNet production logic.
 */
@RestController
@RequestMapping("/lab/v1/http")
class HttpScenarioController {
    /**
     * Echoes any standard request method and its complete textual metadata.
     *
     * @param exchange Active WebFlux exchange.
     * @param body Optional textual request body.
     * @return Deterministic representation of the received request.
     */
    @RequestMapping(
        "/echo",
        method = [
            RequestMethod.GET,
            RequestMethod.HEAD,
            RequestMethod.POST,
            RequestMethod.PUT,
            RequestMethod.PATCH,
            RequestMethod.DELETE,
            RequestMethod.OPTIONS,
        ],
    )
    suspend fun echo(
        exchange: ServerWebExchange,
        @RequestBody(required = false) body: String?,
    ): HttpEchoResponse {
        val request = exchange.request
        return HttpEchoResponse(
            method = request.method.name(),
            path = request.path.value(),
            headers = request.headers.mapValues { (_, values) -> values.toList() },
            query = request.queryParams.mapValues { (_, values) -> values.toList() },
            cookies = request.cookies.mapValues { (_, values) -> values.map { cookie -> cookie.value } },
            bodyText = body,
            receivedAt = Clock.System.now().toString(),
        )
    }

    /**
     * Returns the requested final HTTP status code.
     *
     * @param status Final response status constrained to 200 through 599.
     * @return Small body carrying the effective status code.
     */
    @GetMapping("/status")
    fun status(@RequestParam(defaultValue = "418") status: Int): ResponseEntity<Map<String, Int>> {
        val effectiveStatus = status.coerceIn(MIN_FINAL_STATUS, MAX_STATUS)
        return ResponseEntity
            .status(HttpStatusCode.valueOf(effectiveStatus))
            .body(mapOf("status" to effectiveStatus))
    }

    /**
     * Produces bounded non-blocking response latency.
     *
     * @param millis Requested delay in milliseconds, clamped to the lab safety limit.
     * @return Effective delay value.
     */
    @GetMapping("/delay")
    suspend fun delayed(@RequestParam(defaultValue = "1000") millis: Long): Map<String, Long> {
        val effectiveDelay = millis.coerceIn(0L, MAX_DELAY_MILLIS)
        delay(effectiveDelay.milliseconds)
        return mapOf("delayedMillis" to effectiveDelay)
    }

    /**
     * Produces a bounded redirect to another local lab endpoint.
     *
     * @param status Supported redirect status: 301, 302, 307, or 308.
     * @return Empty redirect response targeting the HTTP echo endpoint.
     */
    @GetMapping("/redirect")
    fun redirect(@RequestParam(defaultValue = "302") status: Int): ResponseEntity<Void> {
        val redirectStatus = when (status) {
            301 -> HttpStatus.MOVED_PERMANENTLY
            307 -> HttpStatus.TEMPORARY_REDIRECT
            308 -> HttpStatus.PERMANENT_REDIRECT
            else -> HttpStatus.FOUND
        }
        return ResponseEntity.status(redirectStatus)
            .location(URI.create("/lab/v1/http/echo?redirected=true"))
            .build()
    }

    /**
     * Returns the cookies supplied by the caller.
     *
     * @param exchange Active exchange containing request cookies.
     * @return Cookie names mapped to every repeated value.
     */
    @GetMapping("/cookies")
    fun cookies(exchange: ServerWebExchange): Map<String, List<String>> = exchange.request.cookies
        .mapValues { (_, values) -> values.map { cookie -> cookie.value } }

    /**
     * Emits two independent Set-Cookie fields so repeated-header preservation can be verified.
     *
     * @return Confirmation response with session and preference cookies.
     */
    @GetMapping("/cookies/set")
    fun setCookies(): ResponseEntity<Map<String, Boolean>> {
        val sessionCookie = ResponseCookie.from("knet_session", "local-test-session")
            .httpOnly(true)
            .sameSite("Lax")
            .path("/")
            .maxAge(COOKIE_MAX_AGE_SECONDS)
            .build()
        val preferenceCookie = ResponseCookie.from("knet_theme", "dark")
            .sameSite("Lax")
            .path("/")
            .maxAge(COOKIE_MAX_AGE_SECONDS)
            .build()
        return ResponseEntity.ok()
            .header(HttpHeaders.SET_COOKIE, sessionCookie.toString(), preferenceCookie.toString())
            .body(mapOf("cookiesSet" to true))
    }

    /**
     * Validates the presence of a Bearer authorization value without validating a real credential.
     *
     * @param authorization Optional Authorization header.
     * @return Authentication result and corresponding 200 or 401 status.
     */
    @GetMapping("/auth/bearer")
    fun bearer(
        @RequestHeader(HttpHeaders.AUTHORIZATION, required = false) authorization: String?,
    ): ResponseEntity<AuthenticationResult> = authenticationResponse(
        accepted = authorization?.startsWith("Bearer ", ignoreCase = true) == true,
        scheme = "Bearer",
    )

    /**
     * Validates the presence of a Basic authorization value without decoding a real credential.
     *
     * @param authorization Optional Authorization header.
     * @return Authentication result and corresponding 200 or 401 status.
     */
    @GetMapping("/auth/basic")
    fun basic(
        @RequestHeader(HttpHeaders.AUTHORIZATION, required = false) authorization: String?,
    ): ResponseEntity<AuthenticationResult> = authenticationResponse(
        accepted = authorization?.startsWith("Basic ", ignoreCase = true) == true,
        scheme = "Basic",
    )

    /**
     * Validates an API key supplied through the dedicated test header.
     *
     * @param apiKey Optional test API key.
     * @return Authentication result and corresponding 200 or 401 status.
     */
    @GetMapping("/auth/api-key")
    fun apiKey(
        @RequestHeader("X-API-Key", required = false) apiKey: String?,
    ): ResponseEntity<AuthenticationResult> = authenticationResponse(
        accepted = !apiKey.isNullOrBlank(),
        scheme = "ApiKey",
    )

    private fun authenticationResponse(
        accepted: Boolean,
        scheme: String,
    ): ResponseEntity<AuthenticationResult> = ResponseEntity
        .status(if (accepted) HttpStatus.OK else HttpStatus.UNAUTHORIZED)
        .body(AuthenticationResult(authenticated = accepted, scheme = scheme))

    private companion object {
        const val MIN_FINAL_STATUS = 200
        const val MAX_STATUS = 599
        const val MAX_DELAY_MILLIS = 30_000L
        const val COOKIE_MAX_AGE_SECONDS = 3_600L
    }
}
