package com.devuloopers.knet.ui.apistudio.scriptanalyzer.model

/**
 * Diagnostic severity level for editor feedback messages.
 */
enum class DiagnosticSeverity {
    HINT,
    INFO,
    WARNING,
    ERROR
}

/**
 * Text range model representing character start and end offsets within script source code.
 *
 * @property startOffset 0-indexed start character index.
 * @property endOffset 0-indexed end character index.
 */
data class TextRange(
    val startOffset: Int,
    val endOffset: Int
)

/**
 * Sealed interface representing editor diagnostic messages generated by [ScriptAnalyzer].
 */
sealed interface ScriptDiagnostic {
    val severity: DiagnosticSeverity
    val message: String
    val range: TextRange?
    val quickFixes: List<ScriptQuickFix>

    /**
     * Pre-request phase warning when pm.response or pm.test assertions are used in Pre-request scripts.
     */
    data class PreRequestAssertionWarning(
        override val message: String = "pm.response and pm.test assertions belong in the Tests tab.",
        override val range: TextRange? = null,
        override val quickFixes: List<ScriptQuickFix> = emptyList()
    ) : ScriptDiagnostic {
        override val severity: DiagnosticSeverity = DiagnosticSeverity.WARNING
    }

    /**
     * General warning diagnostic entry.
     */
    data class GeneralWarning(
        override val message: String,
        override val range: TextRange? = null,
        override val quickFixes: List<ScriptQuickFix> = emptyList()
    ) : ScriptDiagnostic {
        override val severity: DiagnosticSeverity = DiagnosticSeverity.WARNING
    }

    /**
     * General info/hint diagnostic entry.
     */
    data class GeneralHint(
        override val message: String,
        override val range: TextRange? = null,
        override val quickFixes: List<ScriptQuickFix> = emptyList()
    ) : ScriptDiagnostic {
        override val severity: DiagnosticSeverity = DiagnosticSeverity.HINT
    }
}
