package com.devuloopers.knet.engine.websocket

import com.devuloopers.knet.application.contract.apistudio.ApiStudioProtocolDocument
import com.devuloopers.knet.domain.request.descriptor.RequestKindId
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import kotlinx.serialization.json.put

/** Kind of one API Studio-authored WebSocket outbound message. */
enum class WebSocketAuthoredMessageKind {
    TEXT,
    BINARY_BASE64,
}

/**
 * One ordered authored message retained by a WebSocket API Studio draft.
 *
 * @property kind Determines whether [content] is UTF-8 text or Base64-encoded binary data.
 * @property content Presentation-safe authored payload, limited by [MAXIMUM_AUTHORED_BYTES].
 * @throws IllegalArgumentException when the encoded content exceeds the authoring limit.
 */
data class WebSocketAuthoredMessage(
    val kind: WebSocketAuthoredMessageKind,
    val content: String,
) {
    init {
        require(content.encodeToByteArray().size <= MAXIMUM_AUTHORED_BYTES) {
            "Authored WebSocket message exceeds its limit."
        }
    }

    companion object {
        /** Maximum encoded bytes retained for one authored outbound message. */
        const val MAXIMUM_AUTHORED_BYTES: Int = 16 * 1_024 * 1_024
    }
}

/**
 * Ordered optional HTTP header included in an API Studio WebSocket handshake.
 *
 * @property name Valid HTTP field name not owned by the WebSocket client implementation.
 * @property value Header value forwarded during the handshake.
 * @property enabled Whether the header is included during execution.
 * @throws IllegalArgumentException when [name] is blank, malformed, or generated by the client.
 */
data class WebSocketHandshakeHeader(
    val name: String,
    val value: String,
    val enabled: Boolean = true,
) {
    init {
        require(name.isNotBlank()) { "WebSocket handshake header name must not be blank." }
        require(!name.startsWith(':')) { "HTTP pseudo-headers cannot be authored for WebSocket." }
        require(name.matches(HTTP_TOKEN)) { "WebSocket handshake header name is invalid." }
        require(name.lowercase() !in GENERATED_HANDSHAKE_HEADERS) {
            "Header '$name' is generated by the WebSocket client and cannot be overridden."
        }
    }

    private companion object {
        val HTTP_TOKEN: Regex = Regex("[!#$%&'*+.^_`|~0-9A-Za-z-]+")
        val GENERATED_HANDSHAKE_HEADERS: Set<String> = setOf(
            "connection",
            "host",
            "sec-websocket-extensions",
            "sec-websocket-key",
            "sec-websocket-protocol",
            "sec-websocket-version",
            "upgrade",
        )
    }
}

/**
 * Typed WebSocket request draft owned by the WebSocket engine.
 *
 * @property url Absolute `ws` or `wss` endpoint.
 * @property subprotocols Ordered handshake subprotocol preferences.
 * @property headers Optional caller-authored handshake headers.
 * @property connectTimeoutMillis Positive connection deadline in milliseconds.
 * @property outboundMessages Ordered messages used by one-shot execution.
 * @throws IllegalArgumentException when endpoint, timeout, or subprotocol invariants are invalid.
 */
data class WebSocketRequestDraft(
    val url: String,
    val subprotocols: List<String> = emptyList(),
    val headers: List<WebSocketHandshakeHeader> = emptyList(),
    val connectTimeoutMillis: Long = 30_000L,
    val outboundMessages: List<WebSocketAuthoredMessage> = emptyList(),
) {
    init {
        require(url.startsWith("ws://") || url.startsWith("wss://")) {
            "WebSocket URL must use ws or wss."
        }
        require(connectTimeoutMillis in 1L..3_600_000L) { "WebSocket connect timeout is invalid." }
        require(subprotocols.distinct().size == subprotocols.size) { "WebSocket subprotocols must be unique." }
        require(subprotocols.all { protocol -> protocol.matches(SUBPROTOCOL_TOKEN) }) {
            "WebSocket subprotocol values must be valid HTTP tokens."
        }
    }

    private companion object {
        val SUBPROTOCOL_TOKEN: Regex = Regex("[!#$%&'*+.^_`|~0-9A-Za-z-]+")
    }
}

/** Strict versioned codec shared by WebSocket persistence and execution. */
class WebSocketRequestDraftCodec(
    private val json: Json = Json { ignoreUnknownKeys = false },
) {
    /** Encodes one validated draft as an opaque API Studio protocol document. */
    fun encode(id: String, name: String, draft: WebSocketRequestDraft): ApiStudioProtocolDocument {
        val root = buildJsonObject {
            put("url", draft.url)
            put("connectTimeoutMillis", draft.connectTimeoutMillis)
            put("subprotocols", JsonArray(draft.subprotocols.map(::JsonPrimitive)))
            put("headers", buildJsonArray {
                draft.headers.forEach { header ->
                    add(buildJsonObject {
                        put("name", header.name)
                        put("value", header.value)
                        put("enabled", header.enabled)
                    })
                }
            })
            put("outboundMessages", buildJsonArray {
                draft.outboundMessages.forEach { message ->
                    add(buildJsonObject {
                        put("kind", message.kind.name)
                        put("content", message.content)
                    })
                }
            })
        }
        return ApiStudioProtocolDocument(
            id = id,
            name = name,
            kind = RequestKindId.WEBSOCKET,
            schemaVersion = SCHEMA_VERSION,
            payload = root.toString().encodeToByteArray(),
        )
    }

    /** Decodes and validates an opaque WebSocket protocol document. */
    fun decode(document: ApiStudioProtocolDocument): Result<WebSocketRequestDraft> = runCatching {
        require(document.kind == RequestKindId.WEBSOCKET) { "Document is not a WebSocket draft." }
        require(document.schemaVersion == SCHEMA_VERSION) { "Unsupported WebSocket draft schema version." }
        val root = json.parseToJsonElement(document.copyPayload().decodeToString()).jsonObject
        WebSocketRequestDraft(
            url = root.requiredString("url"),
            connectTimeoutMillis = root.getValue("connectTimeoutMillis").jsonPrimitive.long,
            subprotocols = root.arrayOrEmpty("subprotocols").map { element ->
                requireNotNull(element.jsonPrimitive.contentOrNull) { "Invalid WebSocket subprotocol." }
            },
            headers = root.arrayOrEmpty("headers").map { element ->
                val header = element.jsonObject
                WebSocketHandshakeHeader(
                    name = header.requiredString("name"),
                    value = header.requiredString("value"),
                    enabled = header.getValue("enabled").jsonPrimitive.boolean,
                )
            },
            outboundMessages = root.arrayOrEmpty("outboundMessages").map { element ->
                val message = element.jsonObject
                WebSocketAuthoredMessage(
                    kind = WebSocketAuthoredMessageKind.valueOf(message.requiredString("kind")),
                    content = message.requiredString("content"),
                )
            },
        )
    }

    private fun JsonObject.requiredString(name: String): String =
        requireNotNull(this[name]?.jsonPrimitive?.contentOrNull) { "Missing WebSocket draft field '$name'." }

    private fun JsonObject.arrayOrEmpty(name: String): JsonArray = this[name]?.jsonArray ?: JsonArray(emptyList())

    companion object {
        /** Current opaque WebSocket execution-document schema version. */
        const val SCHEMA_VERSION: Int = 1
    }
}
