package com.devuloopers.knet.engine.protocol.grpc

import com.devuloopers.knet.core.logger.KNetLogger
import com.google.protobuf.DescriptorProtos
import com.google.protobuf.Descriptors
import com.google.protobuf.DynamicMessage
import com.google.protobuf.util.JsonFormat
import java.util.concurrent.ConcurrentHashMap

private const val TAG = "ProtobufDynamicDecoder"

/**
 * Dynamic decoder parsing raw Protobuf binary payloads into human-readable JSON using registered descriptors.
 */
class ProtobufDynamicDecoder {

    private val descriptors = ConcurrentHashMap<String, Descriptors.Descriptor>()

    /**
     * Registers a compiled Protobuf descriptor set (.desc or .pb file generated by protoc).
     *
     * @param descriptorSetBytes Binary content of compiled descriptor set file.
     */
    fun registerSchema(descriptorSetBytes: ByteArray) {
        try {
            val fileDescriptorSet = DescriptorProtos.FileDescriptorSet.parseFrom(descriptorSetBytes)
            val fileDescriptors = mutableMapOf<String, Descriptors.FileDescriptor>()

            val pendingProtos = fileDescriptorSet.fileList.toMutableList()
            var progress = true

            while (pendingProtos.isNotEmpty() && progress) {
                progress = false
                val iterator = pendingProtos.iterator()
                while (iterator.hasNext()) {
                    val proto = iterator.next()
                    val dependencies = proto.dependencyList.mapNotNull { fileDescriptors[it] }.toTypedArray()

                    if (dependencies.size == proto.dependencyCount) {
                        val fileDescriptor = Descriptors.FileDescriptor.buildFrom(proto, dependencies)
                        fileDescriptors[proto.name] = fileDescriptor
                        registerMessageTypes(fileDescriptor)

                        iterator.remove()
                        progress = true
                    }
                }
            }

            if (pendingProtos.isNotEmpty()) {
                KNetLogger.warn(TAG) {
                    "Some descriptors could not be registered due to missing dependencies: " +
                        pendingProtos.joinToString { it.name }
                }
            } else {
                KNetLogger.debug(TAG) { "Successfully registered protobuf schema descriptor set." }
            }
        } catch (exception: Exception) {
            KNetLogger.error(TAG, exception) { "Failed to register protobuf schema" }
        }
    }

    private fun registerMessageTypes(fileDescriptor: Descriptors.FileDescriptor) {
        for (descriptor in fileDescriptor.messageTypes) {
            registerDescriptor(descriptor)
        }
    }

    private fun registerDescriptor(descriptor: Descriptors.Descriptor) {
        descriptors[descriptor.fullName] = descriptor
        for (nestedType in descriptor.nestedTypes) {
            registerDescriptor(nestedType)
        }
    }

    /**
     * Decodes a raw protobuf binary payload into a JSON formatted string.
     *
     * @param messageTypeName Fully-qualified name of the message type (e.g. "com.example.User").
     * @param payload Raw serialized protobuf byte array.
     * @return JSON string representation, or structured failure string if decoding fails or schema is missing.
     */
    fun decodeToJson(messageTypeName: String, payload: ByteArray): String? {
        val descriptor = descriptors[messageTypeName] ?: run {
            KNetLogger.warn(TAG) { "No registered descriptor found for type: $messageTypeName" }
            return "{\"error\": \"Unknown message type: $messageTypeName\"}"
        }

        return try {
            val dynamicMessage = DynamicMessage.parseFrom(descriptor, payload)
            JsonFormat.printer().print(dynamicMessage)
        } catch (exception: Exception) {
            KNetLogger.error(TAG, exception) { "Failed to dynamically decode message of type $messageTypeName" }
            "{\"error\": \"Corrupt or invalid payload bytes for type: $messageTypeName\"}"
        }
    }

    /**
     * Clears all registered descriptors from the decoder registry.
     */
    fun clearRegistry() {
        descriptors.clear()
        KNetLogger.debug(TAG) { "Protobuf registry cleared." }
    }
}
