package com.devuloopers.knet.engine.proxy.http

import io.netty.handler.codec.http.FullHttpResponse
import io.netty.handler.codec.http.HttpHeaderNames
import io.netty.handler.codec.http.HttpHeaderValues
import io.netty.handler.codec.http.HttpMessage
import io.netty.handler.codec.http.HttpMethod
import io.netty.handler.codec.http.HttpRequest
import io.netty.handler.codec.http.HttpResponse
import io.netty.handler.codec.http.HttpUtil
import io.netty.handler.codec.http.HttpVersion
import io.netty.handler.codec.http.LastHttpContent

private const val PROXY_CONNECTION_HEADER: String = "Proxy-Connection"

/** Immutable downstream HTTP/1 behavior derived before proxy-only headers are removed. */
internal data class HttpOneDownstreamPolicy(
    val version: HttpVersion,
    val persistenceRequested: Boolean,
) {
    val isHttp10: Boolean
        get() = version == HttpVersion.HTTP_1_0
}

/** Closed validation failures enforced before an HTTP/1 request is forwarded. */
internal enum class HttpOneRequestViolation {
    HTTP_1_0_TRANSFER_ENCODING,
}

/**
 * Version-specific HTTP/1 rules kept beside the Netty transport adapter.
 *
 * The shared traffic model records protocol identity, while this object owns only wire behavior: persistence,
 * generated-response versions, and HTTP/1.0 response framing. It deliberately does not leak Netty types outside
 * `:engine:proxy`.
 */
internal object HttpOneSemantics {

    /** Derives client-facing connection policy, including legacy `Proxy-Connection: keep-alive`. */
    fun downstreamPolicy(request: HttpRequest): HttpOneDownstreamPolicy {
        val proxyConnectionKeepAlive = request.headers()
            .getAll(PROXY_CONNECTION_HEADER)
            .asSequence()
            .flatMap { value -> value.split(',').asSequence() }
            .map(String::trim)
            .any { token -> token.equals(HttpHeaderValues.KEEP_ALIVE.toString(), ignoreCase = true) }
        return HttpOneDownstreamPolicy(
            version = request.protocolVersion(),
            persistenceRequested = HttpUtil.isKeepAlive(request) ||
                (request.protocolVersion() == HttpVersion.HTTP_1_0 && proxyConnectionKeepAlive),
        )
    }

    /** Rejects framing that an HTTP/1.0 recipient cannot define safely. */
    fun validateRequest(request: HttpRequest): HttpOneRequestViolation? = when {
        request.protocolVersion() == HttpVersion.HTTP_1_0 &&
            request.headers().contains(HttpHeaderNames.TRANSFER_ENCODING) ->
            HttpOneRequestViolation.HTTP_1_0_TRANSFER_ENCODING

        else -> null
    }

    /** Removes proxy-only headers and publishes the explicit connection preference to the origin. */
    fun prepareUpstreamRequest(request: HttpRequest, policy: HttpOneDownstreamPolicy) {
        request.headers().remove(PROXY_CONNECTION_HEADER)
        if (policy.isHttp10) {
            request.headers().remove(HttpHeaderNames.TRAILER)
            setPersistence(request, policy.persistenceRequested)
        }
    }

    /** Uses the client's HTTP/1 version for responses generated by KNet itself. */
    fun generatedResponseVersion(requestVersion: HttpVersion): HttpVersion = when (requestVersion) {
        HttpVersion.HTTP_1_0 -> HttpVersion.HTTP_1_0
        else -> HttpVersion.HTTP_1_1
    }

    /** Aligns a provisional response version without applying final-message persistence rules. */
    fun prepareProvisionalResponse(response: HttpResponse, policy: HttpOneDownstreamPolicy) {
        if (policy.isHttp10) response.setProtocolVersion(HttpVersion.HTTP_1_0)
    }

    /**
     * Prepares a final response for the downstream HTTP version and returns whether the connection is reusable.
     *
     * A complete HTTP/1.0 response can receive a content length immediately. A streamed response whose origin used
     * chunked or close-delimited framing instead becomes close-delimited; this retains streaming and bounded memory.
     */
    fun prepareFinalResponse(
        response: HttpResponse,
        requestMethod: HttpMethod,
        policy: HttpOneDownstreamPolicy,
    ): Boolean {
        if (!policy.isHttp10) {
            val keepAlive = policy.persistenceRequested && HttpUtil.isKeepAlive(response)
            setPersistence(response, keepAlive)
            return keepAlive
        }

        response.setProtocolVersion(HttpVersion.HTTP_1_0)
        val responseHasNoBody = responseHasNoBody(requestMethod, response)
        val wasChunked = HttpUtil.isTransferEncodingChunked(response)
        if (wasChunked) HttpUtil.setTransferEncodingChunked(response, false)
        response.headers().remove(HttpHeaderNames.TRAILER)

        if (response is FullHttpResponse && !responseHasNoBody && !HttpUtil.isContentLengthSet(response)) {
            HttpUtil.setContentLength(response, response.content().readableBytes().toLong())
        }

        val isSelfDelimited = responseHasNoBody || HttpUtil.isContentLengthSet(response)
        val keepAlive = policy.persistenceRequested && isSelfDelimited
        setPersistence(response, keepAlive)
        return keepAlive
    }

    /** Drops trailers that cannot be represented on an HTTP/1.0 close-delimited response. */
    fun prepareFinalContent(content: LastHttpContent, policy: HttpOneDownstreamPolicy) {
        if (policy.isHttp10) content.trailingHeaders().clear()
    }

    private fun responseHasNoBody(requestMethod: HttpMethod, response: HttpResponse): Boolean {
        val statusCode = response.status().code()
        return requestMethod == HttpMethod.HEAD ||
            statusCode in 100..199 ||
            statusCode == 204 ||
            statusCode == 304
    }

    private fun setPersistence(message: HttpMessage, keepAlive: Boolean) {
        if (keepAlive) {
            HttpUtil.setKeepAlive(message, true)
        } else {
            message.headers().set(HttpHeaderNames.CONNECTION, HttpHeaderValues.CLOSE)
        }
    }
}
