package com.devuloopers.knet.traffic.id

/**
 * Identifies one bounded traffic-capture session.
 *
 * @property value Stable non-blank identifier generated by the application layer.
 */
@JvmInline
public value class CaptureSessionId(public val value: String) {
    init {
        require(value.isNotBlank()) { "CaptureSessionId must not be blank." }
    }
}

/**
 * Identifies one downstream client connection for its complete lifetime.
 *
 * @property value Stable non-blank identifier generated when the connection is admitted.
 */
@JvmInline
public value class ConnectionId(public val value: String) {
    init {
        require(value.isNotBlank()) { "ConnectionId must not be blank." }
    }
}

/**
 * Identifies one logical request/response exchange independently from its connection.
 *
 * @property value Stable non-blank identifier shared by capture, storage, inspection, and presentation.
 */
@JvmInline
public value class ExchangeId(public val value: String) {
    init {
        require(value.isNotBlank()) { "ExchangeId must not be blank." }
    }
}

/**
 * Identifies a multiplexed application-protocol stream when the protocol provides one.
 *
 * HTTP/1 exchanges normally omit this value. HTTP/2 and HTTP/3 adapters preserve their
 * native stream identifier here without exposing transport-specific stream implementations.
 *
 * @property value Non-negative protocol stream identifier.
 */
@JvmInline
public value class StreamId(public val value: Long) {
    init {
        require(value >= 0L) { "StreamId must not be negative." }
    }
}

/**
 * Identifies body content managed by a bounded body store.
 *
 * The value is an opaque storage key. It is not a filesystem path and must not be derived
 * from a URL, host name, certificate alias, or other user-controlled value.
 *
 * @property value Stable non-blank opaque body identifier.
 */
@JvmInline
public value class BodyId(public val value: String) {
    init {
        require(value.isNotBlank()) { "BodyId must not be blank." }
    }
}
