package com.devuloopers.knet.companion.data.android

import android.content.Context
import android.content.SharedPreferences
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import com.devuloopers.knet.companion.data.store.CompanionRecordStore
import com.devuloopers.knet.companion.data.store.CompanionSecretStore
import com.devuloopers.knet.companion.application.contract.CompanionDeviceIdentityProvider
import com.devuloopers.knet.companion.application.contract.CompanionDeviceProofSigner
import com.devuloopers.knet.companion.model.CompanionDeviceIdentity
import com.devuloopers.knet.identity.RegisteredDeviceId
import com.devuloopers.knet.pairing.DeviceProofAlgorithm
import java.security.KeyPairGenerator
import java.security.KeyStore
import java.security.MessageDigest
import java.security.Signature
import java.security.spec.ECGenParameterSpec
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/** Android non-secret registration store. Shared code owns the versioned record schema. */
public class AndroidCompanionRecordStore(context: Context) : CompanionRecordStore {
    private val preferences: SharedPreferences = context.applicationContext.getSharedPreferences(
        REGISTRATION_PREFERENCES,
        Context.MODE_PRIVATE,
    )
    private val mutableContent: MutableStateFlow<String?> = MutableStateFlow(preferences.getString(CONTENT_KEY, null))

    override val content: StateFlow<String?> = mutableContent.asStateFlow()

    override suspend fun write(content: String?) {
        val editor = preferences.edit()
        if (content == null) editor.remove(CONTENT_KEY) else editor.putString(CONTENT_KEY, content)
        check(editor.commit()) { "Unable to persist companion registration state." }
        mutableContent.value = content
    }

    private companion object {
        const val REGISTRATION_PREFERENCES: String = "knet_companion_registrations"
        const val CONTENT_KEY: String = "versioned_content"
    }
}

/** AES-GCM credential vault whose non-exportable key is generated by Android Keystore. */
public class AndroidKeystoreCompanionSecretStore(context: Context) : CompanionSecretStore {
    private val preferences: SharedPreferences = context.applicationContext.getSharedPreferences(
        SECRET_PREFERENCES,
        Context.MODE_PRIVATE,
    )

    override suspend fun write(key: String, value: String) {
        require(key.isNotBlank() && value.isNotBlank())
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        cipher.updateAAD(key.encodeToByteArray())
        val encrypted = cipher.doFinal(value.encodeToByteArray())
        val encoded = "$SECRET_FORMAT_VERSION.${base64(cipher.iv)}.${base64(encrypted)}"
        check(preferences.edit().putString(key, encoded).commit()) { "Unable to persist companion credential." }
    }

    override suspend fun read(key: String): String? {
        val encoded = preferences.getString(key, null) ?: return null
        return runCatching {
            val fields = encoded.split('.')
            require(fields.size == 3 && fields[0] == SECRET_FORMAT_VERSION)
            val initializationVector = decodeBase64(fields[1])
            val encrypted = decodeBase64(fields[2])
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(GCM_TAG_BITS, initializationVector))
            cipher.updateAAD(key.encodeToByteArray())
            cipher.doFinal(encrypted).decodeToString(throwOnInvalidSequence = true)
        }.getOrNull()
    }

    override suspend fun remove(key: String) {
        check(preferences.edit().remove(key).commit()) { "Unable to delete companion credential." }
    }

    private fun secretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
        (keyStore.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }
        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER).run {
            init(
                KeyGenParameterSpec.Builder(
                    KEY_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                ).setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setRandomizedEncryptionRequired(true)
                    .build(),
            )
            generateKey()
        }
    }

    private fun base64(value: ByteArray): String = Base64.encodeToString(value, Base64.NO_WRAP)
    private fun decodeBase64(value: String): ByteArray = Base64.decode(value, Base64.NO_WRAP)

    private companion object {
        const val SECRET_PREFERENCES: String = "knet_companion_secrets"
        const val KEYSTORE_PROVIDER: String = "AndroidKeyStore"
        const val KEY_ALIAS: String = "knet.companion.credentials.v1"
        const val SECRET_FORMAT_VERSION: String = "v1"
        const val TRANSFORMATION: String = "AES/GCM/NoPadding"
        const val GCM_TAG_BITS: Int = 128
    }
}

/** Persistent P-256 proof identity backed by a non-exportable Android Keystore private key. */
public class AndroidKeystoreCompanionDeviceIdentityProvider : CompanionDeviceIdentityProvider {
    override suspend fun getOrCreate(): CompanionDeviceIdentity {
        val keyStore = loadKeyStore()
        if (!keyStore.containsAlias(DEVICE_KEY_ALIAS)) {
            KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_EC, KEYSTORE_PROVIDER).run {
                initialize(
                    KeyGenParameterSpec.Builder(
                        DEVICE_KEY_ALIAS,
                        KeyProperties.PURPOSE_SIGN or KeyProperties.PURPOSE_VERIFY,
                    ).setAlgorithmParameterSpec(ECGenParameterSpec("secp256r1"))
                        .setDigests(KeyProperties.DIGEST_SHA256)
                        .setUserAuthenticationRequired(false)
                        .build(),
                )
                generateKeyPair()
            }
        }
        val publicKey = checkNotNull(loadKeyStore().getCertificate(DEVICE_KEY_ALIAS)?.publicKey) {
            "Android Keystore did not return the companion public key."
        }
        val publicKeyEncoded = Base64.encodeToString(publicKey.encoded, Base64.NO_WRAP or Base64.URL_SAFE)
            .trimEnd('=')
        val stableId = MessageDigest.getInstance("SHA-256").digest(publicKey.encoded).copyOf(18)
        return CompanionDeviceIdentity(
            deviceId = RegisteredDeviceId(
                Base64.encodeToString(stableId, Base64.NO_WRAP or Base64.URL_SAFE).trimEnd('='),
            ),
            proofAlgorithm = DeviceProofAlgorithm.ECDSA_P256_SHA256,
            publicKeyEncoded = publicKeyEncoded,
            privateKeyReference = DEVICE_KEY_ALIAS,
        )
    }

    private fun loadKeyStore(): KeyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }

    private companion object {
        const val KEYSTORE_PROVIDER: String = "AndroidKeyStore"
        const val DEVICE_KEY_ALIAS: String = "knet.companion.device-proof.v1"
    }
}

/** Signs pairing transcripts without exporting the companion private key. */
public class AndroidKeystoreCompanionDeviceProofSigner : CompanionDeviceProofSigner {
    override suspend fun sign(identity: CompanionDeviceIdentity, message: String): String {
        require(identity.proofAlgorithm == DeviceProofAlgorithm.ECDSA_P256_SHA256) {
            "Android proof signer received an unsupported algorithm."
        }
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
        val privateKey = checkNotNull(keyStore.getKey(identity.privateKeyReference, null)) {
            "Companion proof key is unavailable."
        }
        val signature = Signature.getInstance("SHA256withECDSA").run {
            initSign(privateKey as java.security.PrivateKey)
            update(message.encodeToByteArray())
            sign()
        }
        return Base64.encodeToString(signature, Base64.NO_WRAP or Base64.URL_SAFE).trimEnd('=')
    }

    private companion object {
        const val KEYSTORE_PROVIDER: String = "AndroidKeyStore"
    }
}
