package com.devuloopers.knet.companion.data.android

import android.content.Context
import android.content.SharedPreferences
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import com.devuloopers.knet.companion.data.store.CompanionSecretStore
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.Dispatchers

/** AES-GCM credential vault whose non-exportable key is generated by Android Keystore. */
public class AndroidKeystoreCompanionSecretStore private constructor(
    private val preferences: SharedPreferences,
    private val blockingCalls: AndroidBlockingCallExecutor,
) : CompanionSecretStore {
    override suspend fun write(key: String, value: String) {
        require(key.isNotBlank() && value.isNotBlank())
        blockingCalls.execute {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, secretKey())
            cipher.updateAAD(key.encodeToByteArray())
            val encrypted = cipher.doFinal(value.encodeToByteArray())
            val encoded = "$SECRET_FORMAT_VERSION.${base64(cipher.iv)}.${base64(encrypted)}"
            check(preferences.edit().putString(key, encoded).commit()) {
                "Unable to persist companion credential."
            }
        }
    }

    override suspend fun read(key: String): String? = blockingCalls.execute {
        val encoded = preferences.getString(key, null) ?: return@execute null
        runCatching {
            val fields = encoded.split('.')
            require(fields.size == 3 && fields[0] == SECRET_FORMAT_VERSION)
            val initializationVector = decodeBase64(fields[1])
            val encrypted = decodeBase64(fields[2])
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(GCM_TAG_BITS, initializationVector))
            cipher.updateAAD(key.encodeToByteArray())
            cipher.doFinal(encrypted).decodeToString(throwOnInvalidSequence = true)
        }.getOrNull()
    }

    override suspend fun remove(key: String) {
        blockingCalls.execute {
            check(preferences.edit().remove(key).commit()) { "Unable to delete companion credential." }
        }
    }

    private fun secretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
        (keyStore.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }
        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER).run {
            init(
                KeyGenParameterSpec.Builder(
                    KEY_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                ).setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setRandomizedEncryptionRequired(true)
                    .build(),
            )
            generateKey()
        }
    }

    private fun base64(value: ByteArray): String = Base64.encodeToString(value, Base64.NO_WRAP)

    private fun decodeBase64(value: String): ByteArray = Base64.decode(value, Base64.NO_WRAP)

    public companion object {
        /**
         * Opens the encrypted credential store without blocking the caller's coroutine dispatcher.
         *
         * @param context Android owner whose application context supplies process-scoped preferences.
         * @param ioDispatcher worker dispatcher used for preference and Android Keystore operations.
         * @return initialized Android credential vault.
         */
        public suspend fun create(
            context: Context,
            ioDispatcher: CoroutineDispatcher = Dispatchers.IO,
        ): AndroidKeystoreCompanionSecretStore {
            val blockingCalls = AndroidBlockingCallExecutor(ioDispatcher)
            return blockingCalls.execute {
                AndroidKeystoreCompanionSecretStore(
                    preferences = context.applicationContext.getSharedPreferences(
                        SECRET_PREFERENCES,
                        Context.MODE_PRIVATE,
                    ),
                    blockingCalls = blockingCalls,
                )
            }
        }

        private const val SECRET_PREFERENCES: String = "knet_companion_secrets"
        private const val KEYSTORE_PROVIDER: String = "AndroidKeyStore"
        private const val KEY_ALIAS: String = "knet.companion.credentials.v1"
        private const val SECRET_FORMAT_VERSION: String = "v1"
        private const val TRANSFORMATION: String = "AES/GCM/NoPadding"
        private const val GCM_TAG_BITS: Int = 128
    }
}
