package com.devuloopers.knet.companion.data.android

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import com.devuloopers.knet.companion.data.store.CompanionSecretProtector
import com.devuloopers.knet.companion.data.store.ProtectedCompanionSecret
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.Dispatchers
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import kotlin.io.encoding.Base64

/** AES-GCM protector whose non-exportable key is generated by Android Keystore. */
internal class AndroidKeystoreCompanionSecretProtector(
    ioDispatcher: CoroutineDispatcher = Dispatchers.IO,
) : CompanionSecretProtector {
    private val blockingCalls: AndroidBlockingCallExecutor = AndroidBlockingCallExecutor(ioDispatcher)

    override suspend fun protect(key: String, value: String): ProtectedCompanionSecret {
        require(key.isNotBlank() && value.isNotBlank())
        return blockingCalls.execute {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, secretKey())
            cipher.updateAAD(key.encodeToByteArray())
            val encrypted = cipher.doFinal(value.encodeToByteArray())
            ProtectedCompanionSecret(
                "$SECRET_FORMAT_VERSION.${Base64.encode(cipher.iv)}.${Base64.encode(encrypted)}",
            )
        }
    }

    override suspend fun reveal(key: String, secret: ProtectedCompanionSecret): String? {
        require(key.isNotBlank())
        return blockingCalls.execute {
            runCatching {
                val fields = secret.serializedValue.split('.')
                require(fields.size == 3 && fields[0] == SECRET_FORMAT_VERSION)
                val initializationVector = Base64.decode(fields[1])
                val encrypted = Base64.decode(fields[2])
                val cipher = Cipher.getInstance(TRANSFORMATION)
                cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(GCM_TAG_BITS, initializationVector))
                cipher.updateAAD(key.encodeToByteArray())
                cipher.doFinal(encrypted).decodeToString(throwOnInvalidSequence = true)
            }.getOrNull()
        }
    }

    private fun secretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
        (keyStore.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }
        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER).run {
            init(
                KeyGenParameterSpec.Builder(
                    KEY_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                ).setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setRandomizedEncryptionRequired(true)
                    .build(),
            )
            generateKey()
        }
    }

    private companion object {
        const val KEYSTORE_PROVIDER: String = "AndroidKeyStore"
        const val KEY_ALIAS: String = "knet.companion.credentials.v1"
        const val SECRET_FORMAT_VERSION: String = "v1"
        const val TRANSFORMATION: String = "AES/GCM/NoPadding"
        const val GCM_TAG_BITS: Int = 128
    }
}
